dist: bionic
language: scala
scala:
   - 3.0.0-M1
env:
- JDK=oraclejdk8
- JDK=openjdk8
- JDK=openjdk11
before_script:
  - jdk_switcher use $JDK
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" test
# - git diff --exit-code # check scalariform
